[package]
name = "ray-tracer"
version = "0.1.0"
authors = ["IDragnev <iddragnev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.17.0"
rand = "0.7.2"
lazy_static = "1.4.0"
clap = "~2.27.0"